services:
  dhis2-db:
    volumes:
      - dhis2-db:/var/lib/postgresql/data
  dhis2:
    volumes:
      - ./esignet_online.jks:/opt/dhis2/esignet_online.jks:ro
  reverse-proxy:
    ports:
      - "80:80"
      - "443:443"
    networks:
      - ehr
    volumes:
      - ./config/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/reverse-proxy/dhis2-mec-fullchain.pem:/dhis2-mec-fullchain.pem:ro
      - ./config/reverse-proxy/dhis2-mec-privkey.pem:/dhis2-mec-privkey.pem:ro
  ehr:
    volumes:
      - ehr-db:/tmp
    environment:
      HAPI_FHIR_TESTER_HOME_SERVER_ADDRESS: https://dhis2.mec.mosip.net/nehr/fhir
      HAPI_FHIR_SERVER_ADDRESS: https://dhis2.mec.mosip.net/nehr/fhir
      SPRING_DATASOURCE_URL: jdbc:h2:file:/tmp/data/h2
  esignet-db:
    volumes:
      - esignet-db:/var/lib/postgresql/data
  mock-relying-party-service:
    environment:
      - ESIGNET_SERVICE_URL=${ESIGNET_SERVICE_URL}
      - ESIGNET_AUD_URL=${ESIGNET_AUD_URL}
      - CLIENT_PRIVATE_KEY=${CLIENT_PRIVATE_KEY}
  fhir-sync-agent:
    environment:
      DHIS2APIURL: http://dhis2:8080/api

volumes:
  dhis2-db:
  esignet-db:
  ehr-db:
