services:
  reverse-proxy:
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    volumes:
      - ./config/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
  ehr:
    ports:
      - "8081:8080"