name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Test esignet-capture-plugin
        run: cd esignet-capture-plugin && yarn install --frozen-lockfile && yarn build && yarn test
      - name: Test fhir-sync-agent
        run: mvn -B clean package -f fhir-sync-agent/pom.xml